//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NodeController {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localize {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localize() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NodeController.Properties.Localize", typeof(Localize).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Original Node Controller data was imported.
        ///Backward compatibility does not provide the transfer of all data, may be required manual adjustments..
        /// </summary>
        internal static string Mod_BackwardСompatibilityMessage {
            get {
                return ResourceManager.GetString("Mod_BackwardСompatibilityMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný WARNING: If you make a new save, you will no longer be able to use original Node Controller on this map..
        /// </summary>
        internal static string Mod_BackwardСompatibilityWarning {
            get {
                return ResourceManager.GetString("Mod_BackwardСompatibilityWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Control node type and shape.
        /// </summary>
        internal static string Mod_Description {
            get {
                return ResourceManager.GetString("Mod_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný - Added auto mode for main slope direction.
        ///- Added red overlay for short segments (short segments lead wrong vehicle speed).
        ///- Added the ability reset only offset to default.
        ///- Added Polish translation.
        ///- Fix default node shape calculation.
        ///- Fix wrong corner calculation on too sloped or too curved segments.
        ///- Fix broken nodes after reload map without close game.
        ///- Fix vehicle trailers disappear.
        ///- Fix road disappear after disasters.
        ///- Fix wrong train twist direction.
        ///- Fix node height in asset e [zbytek řetězce byl zkrácen];.
        /// </summary>
        internal static string Mod_WhatsNewMessage3_0_1 {
            get {
                return ResourceManager.GetString("Mod_WhatsNewMessage3_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný - Fix node height outside available tiles (5x5).
        ///- Fix node center position.
        ///- Fix crosswalk texture.
        ///- Fix creating button duplicates
        ///- Fix despaired &quot;Make end straight&quot; button..
        /// </summary>
        internal static string Mod_WhatsNewMessage3_0_2 {
            get {
                return ResourceManager.GetString("Mod_WhatsNewMessage3_0_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný - Added Portuguese translation..
        /// </summary>
        internal static string Mod_WhatsNewMessage3_0_3 {
            get {
                return ResourceManager.GetString("Mod_WhatsNewMessage3_0_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný - Added missing dependencies and mod conflict checker.
        ///- Removed segments collision between train/metro tracks.
        ///- Fix loading offset if value more then 100m.
        ///- Fix segment direction correction on shifted segment.
        ///- Fix not main segment calculation on sloped node.
        ///- Fix crossing and uturn node type.
        ///- Added Italian translation..
        /// </summary>
        internal static string Mod_WhatsNewMessage3_0_4 {
            get {
                return ResourceManager.GetString("Mod_WhatsNewMessage3_0_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný - Fix segments collision calculation.
        ///- Added Chinese Traditional translation..
        /// </summary>
        internal static string Mod_WhatsNewMessage3_0_5 {
            get {
                return ResourceManager.GetString("Mod_WhatsNewMessage3_0_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný - Added underground mode (hold Shift to select underground node).
        ///- Added nearby nodes overlay.
        ///- Added calculate shift by nearby nodes - set average shift value to node.
        ///- Added calculate shift by intersections - set shift value for all nodes between intersection for smooth transition (like -2,-1,0,+1,+2).
        ///- Added set shift between intersections - set this shift value for all nodes between intersection.
        ///- Added shortcuts, you can bind keys in mod&apos;s options.
        ///- Added the ability to hide marking and cha [zbytek řetězce byl zkrácen];.
        /// </summary>
        internal static string Mod_WhatsNewMessage3_1 {
            get {
                return ResourceManager.GetString("Mod_WhatsNewMessage3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný - Fixed not updating nodes after loading map.
        ///- Added selection step over like in MoveIt. Press Ctrl+Space to step over (you can rebind in mod options).
        ///- Added setting &quot;Node is sloped by default&quot;. By default this option disabled.
        ///- Added the ability to change node type by scroll wheel.
        ///- Added new icon for UUI button.
        ///- Added warning for Linux users about missing libraries..
        /// </summary>
        internal static string Mod_WhatsNewMessage3_1_1 {
            get {
                return ResourceManager.GetString("Mod_WhatsNewMessage3_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný - Added Indonesian, Korean and Malay translations..
        /// </summary>
        internal static string Mod_WhatsNewMessage3_1_2 {
            get {
                return ResourceManager.GetString("Mod_WhatsNewMessage3_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný - Added colored text to tooltips.
        ///- Added the ability to hide original mod button in toolbar If you use UUI mod.
        ///- Added Turkish translation..
        /// </summary>
        internal static string Mod_WhatsNewMessage3_1_3 {
            get {
                return ResourceManager.GetString("Mod_WhatsNewMessage3_1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Bend.
        /// </summary>
        internal static string NodeStyle_Bend {
            get {
                return ResourceManager.GetString("NodeStyle_Bend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Crossing.
        /// </summary>
        internal static string NodeStyle_Crossing {
            get {
                return ResourceManager.GetString("NodeStyle_Crossing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Custom.
        /// </summary>
        internal static string NodeStyle_Custom {
            get {
                return ResourceManager.GetString("NodeStyle_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný End.
        /// </summary>
        internal static string NodeStyle_End {
            get {
                return ResourceManager.GetString("NodeStyle_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Middle.
        /// </summary>
        internal static string NodeStyle_Middle {
            get {
                return ResourceManager.GetString("NodeStyle_Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Stretched.
        /// </summary>
        internal static string NodeStyle_Stretch {
            get {
                return ResourceManager.GetString("NodeStyle_Stretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný UTurn.
        /// </summary>
        internal static string NodeStyle_UTurn {
            get {
                return ResourceManager.GetString("NodeStyle_UTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Calculate shift by intersections.
        /// </summary>
        internal static string Option_CalculateShiftByIntersections {
            get {
                return ResourceManager.GetString("Option_CalculateShiftByIntersections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Calculate shift by nearby nodes.
        /// </summary>
        internal static string Option_CalculateShiftByNearby {
            get {
                return ResourceManager.GetString("Option_CalculateShiftByNearby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Reset offset.
        /// </summary>
        internal static string Option_KeepDefault {
            get {
                return ResourceManager.GetString("Option_KeepDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Main slope direction.
        /// </summary>
        internal static string Option_MainSlopeDirection {
            get {
                return ResourceManager.GetString("Option_MainSlopeDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Auto.
        /// </summary>
        internal static string Option_MainSlopeDirectionAuto {
            get {
                return ResourceManager.GetString("Option_MainSlopeDirectionAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Manually.
        /// </summary>
        internal static string Option_MainSlopeDirectionManually {
            get {
                return ResourceManager.GetString("Option_MainSlopeDirectionManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Make ends straight.
        /// </summary>
        internal static string Option_MakeStraightEnds {
            get {
                return ResourceManager.GetString("Option_MakeStraightEnds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Marking.
        /// </summary>
        internal static string Option_Marking {
            get {
                return ResourceManager.GetString("Option_Marking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Offset.
        /// </summary>
        internal static string Option_Offset {
            get {
                return ResourceManager.GetString("Option_Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný {0}m.
        /// </summary>
        internal static string Option_OffsetFormat {
            get {
                return ResourceManager.GetString("Option_OffsetFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Reset to default.
        /// </summary>
        internal static string Option_ResetToDefault {
            get {
                return ResourceManager.GetString("Option_ResetToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rotate.
        /// </summary>
        internal static string Option_Rotate {
            get {
                return ResourceManager.GetString("Option_Rotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný {0}°.
        /// </summary>
        internal static string Option_RotateFormat {
            get {
                return ResourceManager.GetString("Option_RotateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Set shift between intersections.
        /// </summary>
        internal static string Option_SetShiftBetweenIntersections {
            get {
                return ResourceManager.GetString("Option_SetShiftBetweenIntersections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Shift.
        /// </summary>
        internal static string Option_Shift {
            get {
                return ResourceManager.GetString("Option_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný {0}m.
        /// </summary>
        internal static string Option_ShiftFormat {
            get {
                return ResourceManager.GetString("Option_ShiftFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Slope.
        /// </summary>
        internal static string Option_Slope {
            get {
                return ResourceManager.GetString("Option_Slope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný {0}°.
        /// </summary>
        internal static string Option_SlopeFormat {
            get {
                return ResourceManager.GetString("Option_SlopeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Stretch.
        /// </summary>
        internal static string Option_Stretch {
            get {
                return ResourceManager.GetString("Option_Stretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný {0}%.
        /// </summary>
        internal static string Option_StretchFormat {
            get {
                return ResourceManager.GetString("Option_StretchFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Style.
        /// </summary>
        internal static string Option_Style {
            get {
                return ResourceManager.GetString("Option_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Flat.
        /// </summary>
        internal static string Option_StyleFlat {
            get {
                return ResourceManager.GetString("Option_StyleFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Slope.
        /// </summary>
        internal static string Option_StyleSlope {
            get {
                return ResourceManager.GetString("Option_StyleSlope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Twist.
        /// </summary>
        internal static string Option_Twist {
            get {
                return ResourceManager.GetString("Option_Twist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný {0}°.
        /// </summary>
        internal static string Option_TwistFormat {
            get {
                return ResourceManager.GetString("Option_TwistFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Node type.
        /// </summary>
        internal static string Option_Type {
            get {
                return ResourceManager.GetString("Option_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný All.
        /// </summary>
        internal static string Options_All {
            get {
                return ResourceManager.GetString("Options_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Node #{0}.
        /// </summary>
        internal static string Panel_NodeId {
            get {
                return ResourceManager.GetString("Panel_NodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Calculate shift by intersections.
        /// </summary>
        internal static string Setting_ShortcutCalculateShiftByIntersections {
            get {
                return ResourceManager.GetString("Setting_ShortcutCalculateShiftByIntersections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Calculate shift by nearby nodes.
        /// </summary>
        internal static string Setting_ShortcutCalculateShiftByNearby {
            get {
                return ResourceManager.GetString("Setting_ShortcutCalculateShiftByNearby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Change main slope direction mode.
        /// </summary>
        internal static string Setting_ShortcutChangeMainRoadMode {
            get {
                return ResourceManager.GetString("Setting_ShortcutChangeMainRoadMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Change node style.
        /// </summary>
        internal static string Setting_ShortcutChangeNodeStyle {
            get {
                return ResourceManager.GetString("Setting_ShortcutChangeNodeStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Reset offset.
        /// </summary>
        internal static string Setting_ShortcutKeepDefault {
            get {
                return ResourceManager.GetString("Setting_ShortcutKeepDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Make ends straight.
        /// </summary>
        internal static string Setting_ShortcutMakeStraightEnds {
            get {
                return ResourceManager.GetString("Setting_ShortcutMakeStraightEnds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Reset to default.
        /// </summary>
        internal static string Setting_ShortcutResetToDefault {
            get {
                return ResourceManager.GetString("Setting_ShortcutResetToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Set shift between intersections.
        /// </summary>
        internal static string Setting_ShortcutSetShiftBetweenIntersections {
            get {
                return ResourceManager.GetString("Setting_ShortcutSetShiftBetweenIntersections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Node is sloped by default.
        /// </summary>
        internal static string Settings_NodeIsSlopedByDefault {
            get {
                return ResourceManager.GetString("Settings_NodeIsSlopedByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Show nearby nodes overlay.
        /// </summary>
        internal static string Settings_RenderNearNode {
            get {
                return ResourceManager.GetString("Settings_RenderNearNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Select middle nodes.
        /// </summary>
        internal static string Settings_SelectMiddleNodes {
            get {
                return ResourceManager.GetString("Settings_SelectMiddleNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný If this option is disabled, the middle nodes will move to clicked position.
        /// </summary>
        internal static string Settings_SelectMiddleNodesDiscription {
            get {
                return ResourceManager.GetString("Settings_SelectMiddleNodesDiscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Set to lane edit mode.
        /// </summary>
        internal static string Settings_ShortcutLaneEdit {
            get {
                return ResourceManager.GetString("Settings_ShortcutLaneEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Hold {0} to alignment roads.
        /// </summary>
        internal static string Tool_InfoAlignMode {
            get {
                return ResourceManager.GetString("Tool_InfoAlignMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Click to align with this corner.
        /// </summary>
        internal static string Tool_InfoApplyAlign {
            get {
                return ResourceManager.GetString("Tool_InfoApplyAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Hold {0} see lane editing.
        /// </summary>
        internal static string Tool_InfoChangeMainMode {
            get {
                return ResourceManager.GetString("Tool_InfoChangeMainMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Click to inverse lane direction (full circle outgoing).
        /// </summary>
        internal static string Tool_InfoClickLaneInversion {
            get {
                return ResourceManager.GetString("Tool_InfoClickLaneInversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Node #{0}
        ///Click to edit.
        /// </summary>
        internal static string Tool_InfoClickNode {
            get {
                return ResourceManager.GetString("Tool_InfoClickNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Click to select corner you want to align.
        /// </summary>
        internal static string Tool_InfoClickToSelectFirstAlign {
            get {
                return ResourceManager.GetString("Tool_InfoClickToSelectFirstAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Drag to change offset.
        /// </summary>
        internal static string Tool_InfoDragCenter {
            get {
                return ResourceManager.GetString("Tool_InfoDragCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Drag to change rotate.
        /// </summary>
        internal static string Tool_InfoDragCircle {
            get {
                return ResourceManager.GetString("Tool_InfoDragCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Drag to change corner offset.
        /// </summary>
        internal static string Tool_InfoDragCorner {
            get {
                return ResourceManager.GetString("Tool_InfoDragCorner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Drag this end to change main slope direction.
        /// </summary>
        internal static string Tool_InfoDragMainSlopeDirectionEnd {
            get {
                return ResourceManager.GetString("Tool_InfoDragMainSlopeDirectionEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Drop this end to change main slope direction.
        /// </summary>
        internal static string Tool_InfoDropMainSlopeDirectionEnd {
            get {
                return ResourceManager.GetString("Tool_InfoDropMainSlopeDirectionEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Click to insert crossing node.
        /// </summary>
        internal static string Tool_InfoInsertCrossingNode {
            get {
                return ResourceManager.GetString("Tool_InfoInsertCrossingNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Click to insert node.
        /// </summary>
        internal static string Tool_InfoInsertNode {
            get {
                return ResourceManager.GetString("Tool_InfoInsertNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Hold {0} to switch to lane editing mode.
        /// </summary>
        internal static string Tool_InfoLaneEdit {
            get {
                return ResourceManager.GetString("Tool_InfoLaneEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Select corner you want to align with.
        /// </summary>
        internal static string Tool_InfoSelectAlignRelative {
            get {
                return ResourceManager.GetString("Tool_InfoSelectAlignRelative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Change to desired main slope direction.
        /// </summary>
        internal static string Tool_InfoSelectMainSlopeDirection {
            get {
                return ResourceManager.GetString("Tool_InfoSelectMainSlopeDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Select end position of main slope direction.
        /// </summary>
        internal static string Tool_InfoSelectNewMainSlopeDirectionEnd {
            get {
                return ResourceManager.GetString("Tool_InfoSelectNewMainSlopeDirectionEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Select node.
        /// </summary>
        internal static string Tool_InfoSelectNode {
            get {
                return ResourceManager.GetString("Tool_InfoSelectNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Select corners you want to align.
        /// </summary>
        internal static string Tool_InfoSelectToAlign {
            get {
                return ResourceManager.GetString("Tool_InfoSelectToAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Can&apos;t insert node
        ///Too close to nearby node.
        /// </summary>
        internal static string Tool_InfoTooCloseNode {
            get {
                return ResourceManager.GetString("Tool_InfoTooCloseNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Hold {0} to
        ///underground mode.
        /// </summary>
        internal static string Tool_InfoUnderground {
            get {
                return ResourceManager.GetString("Tool_InfoUnderground", resourceCulture);
            }
        }
    }
}
